name: CI

on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Up docker containers
        run: docker-compose up -d dev
      - name: List containers is running
        run: docker-compose ps
      - name: List images is running
        run: docker images -a
      - name: Run tests with Jest and Converage
        run: docker run -e CI=true cpp-participacao-frontend_dev npm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: coverage/clover.xml
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
