name: PROD_ci

on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Up docker containers
        run: docker-compose up -d prod
      - name: List containers is running
        run: docker-compose ps
      - name: List images is running
        run: docker images -a